[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/registry-assets/r24/manifest.json"
  [headers.values]
    Content-Type = "application/vnd.oci.image.manifest.v1+json"
    Docker-Content-Digest = "sha256:87108e9df86e106041e2cbe82dda5bd1a7c18164153780a7ccf878e55506c686"
    Docker-Distribution-Api-Version = "registry/2.0"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/registry-assets/r24/config.json"
  [headers.values]
    Content-Type = "application/vnd.oci.image.config.v1+json"
    Docker-Content-Digest = "sha256:2945493266e9cffb0de0e98376ed3a853cf0e71ec714be64b8f5e3216a023ec8"
    Docker-Distribution-Api-Version = "registry/2.0"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/registry-assets/r35/manifest.json"
  [headers.values]
    Content-Type = "application/vnd.oci.image.manifest.v1+json"
    Docker-Content-Digest = "sha256:87b90df3c6d7d8a8161ea5d718e97608566bc3e0818fb6e80769a937c68b62fb"
    Docker-Distribution-Api-Version = "registry/2.0"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/registry-assets/r35/config.json"
  [headers.values]
    Content-Type = "application/vnd.oci.image.config.v1+json"
    Docker-Content-Digest = "sha256:34a134780c4539ec52e5bf5873b4899e30b798d7ff81f8dd6e87ae9068082b72"
    Docker-Distribution-Api-Version = "registry/2.0"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/registry-assets/r61/manifest.json"
  [headers.values]
    Content-Type = "application/vnd.oci.image.manifest.v1+json"
    Docker-Content-Digest = "sha256:0205651ae7d2806d3286a22270b5d7e23f1ec3f8ac47ed7352a719feca2e6b07"
    Docker-Distribution-Api-Version = "registry/2.0"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/registry-assets/r61/config.json"
  [headers.values]
    Content-Type = "application/vnd.oci.image.config.v1+json"
    Docker-Content-Digest = "sha256:3649af2042930c40db6ed42f9d4711f96e3ec73be5157d8846416ed5ab18a90c"
    Docker-Distribution-Api-Version = "registry/2.0"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/registry-assets/r61/DEPLOY_COMMIT.txt"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"
    Cache-Control = "no-store"

[[headers]]
  for = "/registry-assets/v3/manifest.json"
  [headers.values]
    Content-Type = "application/vnd.oci.image.manifest.v1+json"
    Docker-Content-Digest = "sha256:2cd44cd0a63ecf1edd61a3aaf0329fd8df22f802eaaa3b5b090d3ff82dc5759d"
    Docker-Distribution-Api-Version = "registry/2.0"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/registry-assets/v3/config.json"
  [headers.values]
    Content-Type = "application/vnd.oci.image.config.v1+json"
    Docker-Content-Digest = "sha256:180056296b31d73e2e725cb376bb5d9601561befd651e8d2a0c554c5d486f37b"
    Docker-Distribution-Api-Version = "registry/2.0"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/registry-assets/v3/455615bc3a018340753f08051ed82fc1b943a62529adb44b9bf2161fc0c503ef.tar.gz"
  [headers.values]
    Content-Type = "application/octet-stream"
    Docker-Content-Digest = "sha256:455615bc3a018340753f08051ed82fc1b943a62529adb44b9bf2161fc0c503ef"
    Cache-Control = "public, max-age=31536000, immutable"
