import test from 'node:test';import assert from 'node:assert/strict';
import {reviseLine,nextMove,studyNote} from '../public/repair-desk.mjs';
import {beginRepair,repairTurn,repairReport,EXAMPLE,REPAIR,reconstruct} from '../src/relay.mjs';
const turn=(s,type,value)=>repairTurn(s.capsule,s.capsule.sha256,{id:String(s.capsule.events.length),type,...(value?{value}:{})});
test('one line changes while original and later work remain untouched',()=>assert.equal(reviseLine(EXAMPLE,1,'2x + 6 = 10'),REPAIR));
test('original problem cannot be selected for replacement',()=>assert.throws(()=>reviseLine(EXAMPLE,0,'x=2'),/after the original/));
test('noninteger and out of range indexes are rejected',()=>{for(const i of [-1,1.5,6,'1',NaN])assert.throws(()=>reviseLine(EXAMPLE,i,'x=2'))});
test('multiline, empty and long replacements are rejected',()=>{for(const value of ['',' ','x=2\nx=3','x=2\rx=3','x'.repeat(301),null])assert.throws(()=>reviseLine(EXAMPLE,1,value))});
test('append preserves all existing work',()=>assert.equal(reviseLine('2x = 4\nx+x=4',2,'x = 2'),'2x = 4\nx+x=4\nx = 2'));
test('line ceiling is enforced for append, existing lines can be changed',()=>{const chain=Array(12).fill('2x=4').join('\n');assert.throws(()=>reviseLine(chain,12,'x=2'),/twelve/);assert.equal(reviseLine(chain,11,'x=2').split('\n').length,12)});
test('normalized blank lines preserve exact original problem semantics',()=>assert.equal(reviseLine(' 2x=4 \r\n\r\n x=3 ',1,'x=2'),'2x=4\nx=2'));
test('first error stays first after one local change reveals a later error',()=>{let s=beginRepair('2(x + 3) = 10\n2x + 3 = 10\n2x = 6\nx = 3');s=turn(s,'repair',reviseLine(s.view.chain,1,'2x + 6 = 10'));assert.equal(s.view.audit.first,2);assert.equal(nextMove(s.view).title,'Repair line 3')});
test('unfinished equivalent work suggests an appended step, not mastery',()=>{let s=beginRepair('2x = 4\nx+x = 4');assert.equal(nextMove(s.view).target,'stepValue');s=turn(s,'repair',reviseLine(s.view.chain,2,'x = 2'));assert.equal(nextMove(s.view).target,'practice')});
test('unsupported replacement remains outside scope rather than wrong',()=>{const s=turn(beginRepair(),'repair',reviseLine(EXAMPLE,1,'x*x = 4'));assert.equal(nextMove(s.view).title,'This step is outside the checker')});
test('guided editing does not reveal an exact witness',()=>{const s=turn(beginRepair(),'repair',reviseLine(EXAMPLE,1,'2x + 7 = 10'));assert.equal(s.view.witness,null);assert.equal(s.view.summary.independent_first_attempts,0)});
test('unstarted guide does not pretend a session exists',()=>assert.equal(nextMove(null).target,'begin'));
test('readable review requires a real shaped report',()=>{for(const r of [null,{}, {summary:{},attempts:[],current_chain:'x=1',source_digest:'a'.repeat(64)}])assert.throws(()=>studyNote(r))});
test('repair is not fresh-number transfer in the note',()=>{const note=studyNote(repairReport(turn(beginRepair(),'repair',REPAIR).capsule));assert.match(note,/No fresh-number answers/);assert.match(note,/not a school grade/)});
test('assisted completion cannot turn independent in readable export',()=>{let s=turn(beginRepair(),'repair',REPAIR);s=turn(s,'practice');s=turn(s,'hint');s=turn(s,'answer',reconstruct(s.capsule).card.good);const r=repairReport(s.capsule),note=studyNote(r);assert.match(note,/Independent first attempts: 0/);assert.match(note,/Assisted completions: 1/);assert(note.includes(r.source_digest))});
test('equivalent alternative and revised work remain distinct in note',()=>{let s=turn(turn(beginRepair(),'repair',REPAIR),'practice');s=turn(s,'answer',s.view.card.before);s=turn(s,'answer',reconstruct(s.capsule).card.good);const note=studyNote(repairReport(s.capsule));assert.match(note,/Equivalent, but a different operation/);assert.match(note,/Revised completions: 1/);assert.match(note,/Independent first attempts: 0/)});
