import test from 'node:test';import assert from 'node:assert/strict';import {Rehearsal,validateTrace} from '../src/engine.mjs';
const h=n=>'0x'+n.toString(16).padStart(64,'0'),addr='0x'+'1'.repeat(40),account='0x'+'2'.repeat(40);
function fixture(){const event=(n,order=99,units='1')=>({orderId:h(order),account,address:addr,units,blockHash:h(n),blockNumber:n===20?2:2,transactionHash:h(n+100),logIndex:0});return {version:1,chainId:'31337',contract:addr,anchor:h(1),blocks:[{hash:h(1),parentHash:h(0),number:1,events:[]},{hash:h(2),parentHash:h(1),number:2,events:[event(2)]},{hash:h(3),parentHash:h(2),number:3,events:[]},{hash:h(4),parentHash:h(3),number:4,events:[]},{hash:h(20),parentHash:h(1),number:2,events:[event(20,100)]}],scenarios:[{id:'test',title:'test',heads:[1,2,3,4,20,4].map(n=>({hash:h(n),note:'test'}))}]}}
const start=()=>new Rehearsal(fixture(),'test',3);
test('read does not change state',()=>{const r=start();assert.deepEqual(r.view(),r.view())});
test('three blocks are required including inclusion',()=>{const r=start();r.next();r.next();assert.equal(r.view().ready,0);r.next();assert.equal(r.view().ready,0);r.next();assert.equal(r.view().ready,1)});
test('early delivery rejected',()=>{const r=start();r.next();r.next();assert.throws(()=>r.deliver(r.view().rows[0].eventId,r.view().head.hash),/not eligible/)});
test('stale head cannot authorize delivery',()=>{const r=start();for(let i=0;i<4;i++)r.next();assert.throws(()=>r.deliver(r.view().rows[0].eventId,h(2)),/Head changed/)});
test('duplicate delivery is not counted twice',()=>{const r=start();for(let i=0;i<4;i++)r.next();const e=r.view().rows[0];r.deliver(e.eventId,h(4));r.deliver(e.eventId,h(4));assert.equal(r.view().delivered.length,1)});
test('orphan before delivery is not irreversible debt',()=>{const r=start();for(let i=0;i<5;i++)r.next();assert.equal(r.view().debt,0);assert.equal(r.view().naiveOrphanCredits,1);assert.equal(r.view().halted,false)});
test('deep reorg latches and preserves irreversible delivery',()=>{const r=start();for(let i=0;i<4;i++)r.next();r.deliver(r.view().rows[0].eventId,h(4));r.next();assert(r.view().halted);assert.equal(r.view().debt,1);assert.equal(r.view().delivered.length,1);r.next();assert(r.view().halted);assert.equal(r.view().debt,0);assert.throws(()=>r.deliver(r.view().rows[0].eventId,h(4)),/Incident/)});
test('restored session recomputes all outcomes',()=>{const r=start();for(let i=0;i<4;i++)r.next();r.deliver(r.view().rows[0].eventId,h(4));r.next();assert.deepEqual(Rehearsal.load(r.save()).view(),r.view())});
test('saved file cannot inject ready state',()=>{const r=start();r.next();r.next();const s=r.save();s.ready=99;s.halted=false;assert.equal(Rehearsal.load(s).view().ready,0)});
test('future delivery history rejected',()=>{const r=start();r.next();const s=r.save();s.deliveries=[{cursor:3}];assert.throws(()=>Rehearsal.load(s),/future/)});
test('history units cannot disagree with replay',()=>{const r=start();for(let i=0;i<4;i++)r.next();r.deliver(r.view().rows[0].eventId,h(4));const s=r.save();s.deliveries[0].units='9';assert.throws(()=>Rehearsal.load(s),/mismatch/)});
test('trace input is copied',()=>{const t=fixture(),r=new Rehearsal(t,'test');t.blocks=[];r.next();assert.equal(r.view().head.number,1)});
test('unknown scenario rejected',()=>assert.throws(()=>new Rehearsal(fixture(),'missing')));
for(const [name,mut] of [
 ['version',t=>t.version=2],['emitter',t=>t.blocks[1].events[0].address=account],['duplicate block',t=>t.blocks.push(t.blocks[0])],['event block',t=>t.blocks[1].events[0].blockHash=h(4)],['broken parent',t=>t.blocks[2].parentHash=h(10)],['height',t=>t.blocks[2].number=6],['negative units',t=>t.blocks[1].events[0].units='-1'],['zero units',t=>t.blocks[1].events[0].units='0'],['numeric units',t=>t.blocks[1].events[0].units=1],['invalid account',t=>t.blocks[1].events[0].account='bad'],['missing anchor',t=>t.anchor=h(90)],['anchor events',t=>t.anchor=h(2)],['duplicate log',t=>t.blocks[1].events.push(t.blocks[1].events[0])],['unknown head',t=>t.scenarios[0].heads[0].hash=h(900)],['duplicate scenario',t=>t.scenarios.push(t.scenarios[0])],['long note',t=>t.scenarios[0].heads[0].note='x'.repeat(601)]
])test(`invalid ${name} rejected atomically`,()=>{const t=fixture();mut(t);assert.throws(()=>validateTrace(t))});
for(const n of [0,13,1.5,-1,NaN,'3'])test(`invalid threshold ${n}`,()=>assert.throws(()=>new Rehearsal(fixture(),'test',n)));
for(let threshold=1;threshold<=12;threshold++)test(`confirmation policy ${threshold}`,()=>{const r=new Rehearsal(fixture(),'test',threshold);for(let i=0;i<4;i++)r.next();assert.equal(r.view().ready,threshold<=3?1:0)});
test('duplicate business orders conflict',()=>{const t=fixture();const b=t.blocks[2],e={...t.blocks[1].events[0],blockHash:b.hash,blockNumber:b.number,transactionHash:h(700)};b.events=[e];const r=new Rehearsal(t,'test',1);for(let i=0;i<3;i++)r.next();assert.equal(r.view().ready,0);assert(r.view().rows.every(x=>x.status==='conflict'))});

test('loss of confirmations latches even if event survives',()=>{const t=fixture();t.scenarios[0].heads.push({hash:h(2),note:'head retreat'});const r=new Rehearsal(t,'test',3);for(let i=0;i<4;i++)r.next();r.deliver(r.view().rows[0].eventId,h(4));r.scenario.heads=r.scenario.heads.slice(0,4).concat({hash:h(2),note:'retreat'});r.next();assert(r.view().halted);assert.equal(r.view().debt,0)});
