'use strict';
const R=CountbackReview,C=JSON.parse(document.getElementById('caseData').textContent),$=id=>document.getElementById(id);
let state=null,selected=C.items.findIndex(i=>i.id==='mouse'),verdict=null,dirty=false,revision=0;
if(selected<0)selected=0;
function status(text,error=false){$('status').textContent=text;$('status').className=error?'error':'';}
function draft(on){dirty=on;$('draft').textContent=on?'Unrecorded changes':'';$('export').disabled=on;$('save').disabled=on;}
function safe(fn){return async()=>{try{await fn();}catch(e){status(e.message,true);}};}
function escapeText(s){return String(s).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));}
function download(name,content,type='application/json'){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function labels(v){return {consistent:'Appears consistent',different:'Different / mismatch',unclear:'Still unclear'}[v]||'Pending';}
function current(){return C.items[selected];}
function view(){return current().views.find(v=>v.id===$('viewSelect').value)||current().views[0];}
function showView(){const v=view();$('candidateImage').src=v.crop;$('contextImage').src=v.context;$('candidateNote').textContent=v.caption;$('contextPanel').classList.add('hide');}
function choose(v){verdict=v;document.querySelectorAll('[data-verdict]').forEach(b=>{b.classList.toggle('selected',b.dataset.verdict===v);b.setAttribute('aria-pressed',String(b.dataset.verdict===v));});}
function render(){
 const item=current(),rows=R.latest(C,state),done=rows.filter(r=>r.human_assessment).length;
 $('pending').textContent=`${done} of ${C.items.length} reference labels reviewed`;$('progress').style.width=(done/C.items.length*100)+'%';
 $('references').replaceChildren();C.items.forEach((i,n)=>{const b=document.createElement('button');b.type='button';b.dataset.reference=i.id;b.className=n===selected?'active':'';b.setAttribute('aria-current',n===selected?'true':'false');b.append(document.createTextNode(i.title));const s=document.createElement('small');const row=rows.find(r=>r.reference===i.id);s.textContent=labels(row.human_assessment?.verdict);b.append(s);b.onclick=()=>{if(dirty&&!confirm('Discard the unrecorded changes?'))return;selected=n;revision++;draft(false);render();};$('references').append(b);});
 $('position').textContent=`REFERENCE ${selected+1} / ${C.items.length}`;$('itemTitle').textContent=item.title;$('machineTag').textContent=item.evidence_label;$('intro').textContent=item.instruction;$('machineDetail').textContent=item.evidence_detail;$('referenceImage').src=item.reference_image;$('referenceNote').textContent=item.reference_note;
 $('viewSelect').replaceChildren();item.views.forEach(v=>{const o=document.createElement('option');o.value=v.id;o.textContent=v.label;$('viewSelect').append(o);});$('viewSelect').value=item.suggested_view;
 const latest=rows.find(r=>r.reference===item.id).human_assessment;choose(latest?.verdict||null);$('note').value=latest?.note||'';if(latest){$('reviewer').value=latest.reviewer;$('viewSelect').value=latest.view;}
 $('history').replaceChildren();state.events.filter(e=>e.reference===item.id).slice().reverse().forEach(e=>{const p=document.createElement('div');p.className='history';p.textContent=`${e.sequence}. ${labels(e.verdict)} · ${e.reviewer} · ${e.view} · ${e.recorded_at}\n${e.note}`;$('history').append(p);});if(!$('history').children.length)$('history').textContent='No human assessment has been recorded.';
 $('version').textContent=C.opencv_version;$('trace').textContent=JSON.stringify({evidence_sha256:C.evidence_sha256,input_provenance:C.input_provenance,trace:C.trace},null,2);showView();status('');
}
document.querySelectorAll('[data-verdict]').forEach(b=>b.onclick=()=>{choose(b.dataset.verdict);revision++;draft(true);});
['note','reviewer'].forEach(id=>$(id).oninput=()=>{revision++;draft(true);});
$('viewSelect').onchange=()=>{revision++;showView();if(verdict)draft(true);};
$('showContext').onclick=()=>{$('contextPanel').classList.toggle('hide');if(!$('contextPanel').classList.contains('hide'))$('contextPanel').scrollIntoView({behavior:'smooth',block:'nearest'});};
$('record').onclick=safe(async()=>{const stamp=revision;const proposed=await R.add(C,state,{reference:current().id,view:view().id,verdict,note:$('note').value.trim(),reviewer:$('reviewer').value.trim(),recorded_at:new Date().toISOString()});if(revision!==stamp)throw Error('The form changed while saving. Record the current assessment again.');state=proposed;revision++;draft(false);render();status('Assessment recorded. Automated evidence is unchanged. Save a session to keep your work.');});
$('next').onclick=()=>{if(dirty&&!confirm('Discard the unrecorded changes?'))return;selected=(selected+1)%C.items.length;revision++;draft(false);render();};
$('save').onclick=safe(async()=>{if(dirty)throw Error('Record or discard your draft first.');const stamp=revision,p=await R.pack(C,state);if(stamp!==revision)throw Error('Review changed while preparing download. Try again.');download('Countback-review-session.json',JSON.stringify(p,null,2));status('Session downloaded. Reopen it here to continue the same evidence review.');});
$('load').onclick=()=>{$('sessionFile').click();};
$('sessionFile').onchange=safe(async()=>{const file=$('sessionFile').files[0];$('sessionFile').value='';if(!file)return;if(file.size>2000000)throw Error('Session is too large.');if(dirty&&!confirm('Discard unrecorded form changes and open this session?'))return;const stamp=revision,text=await file.text(),next=await R.restore(C,JSON.parse(text));if(revision!==stamp)throw Error('Current review changed during import. Nothing replaced.');if(state.events.length&&!confirm('Replace the current local review with this saved session?'))return;state=next;revision++;draft(false);render();status('Saved judgments reopened for this exact evidence. They are not authenticated human identity or automated proof.');});
$('export').onclick=safe(async()=>{if(dirty)throw Error('Record or discard your draft first.');const stamp=revision,data=await R.handoff(C,state);if(stamp!==revision)throw Error('Review changed while exporting. Try again.');const json=JSON.stringify(data,null,2),rows=data.items.map(i=>`<tr><td>${escapeText(i.reference)}</td><td>${escapeText(i.automated_evidence)}</td><td>${escapeText(labels(i.human_assessment?.verdict))}</td><td>${escapeText(i.human_assessment?.note||'No human assessment')}</td></tr>`).join('');const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline';"><title>Countback review handoff</title><style>body{font:17px/1.6 system-ui;max-width:1050px;margin:40px auto;padding:20px;color:#15283b}table{border-collapse:collapse;width:100%}td,th{text-align:left;border-bottom:1px solid #ccc;padding:12px}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px}</style><h1>Countback · Operator handoff</h1><p>${data.human_reviewed_reference_labels} of ${data.reference_labels} reference labels have a human assessment. No physical count, condition or kit-completeness conclusion.</p><p><b>Needs attention:</b> ${escapeText(data.attention_required.join(', ')||'No remaining human review items; this does not certify the kit.')}</p><p><b>Still unresolved by automation:</b> ${escapeText(data.automated_unresolved.join(', ')||'None at the configured evidence tiers')}</p><table><tr><th>Reference</th><th>Machine evidence</th><th>Human assessment</th><th>Reason</th></tr>${rows}</table><p>Human judgments do not rewrite machine evidence. Reviewer names and session files are self-reported and editable. Digests are not digital signatures.</p><h2>Evidence and history</h2><pre>${escapeText(json)}</pre></html>`;download('Countback-review-handoff.html',html,'text/html');status('Readable handoff downloaded with evidence fingerprints and review history.');});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
(async()=>{try{state=await R.create(C);render();}catch(e){status(e.message,true);$('record').disabled=$('export').disabled=$('save').disabled=true;}})();
