from pathlib import Path
import subprocess,sys,json,hashlib,zipfile,re,traceback
from datetime import datetime,timezone
R=Path(__file__).resolve().parents[1];E=R/'evidence';E.mkdir(exist_ok=True)
report={'status':'running','started_at':datetime.now(timezone.utc).isoformat(),'commands':[]}
def run(name,args):
 p=subprocess.run(args,cwd=R,capture_output=True,text=True,timeout=300);(E/(name+'.log')).write_text(p.stdout+'\n'+p.stderr);report['commands'].append({'name':name,'exit_code':p.returncode});assert p.returncode==0,(name,p.stdout[-1200:],p.stderr[-1200:]);return p.stdout
try:
 run('path-build',[sys.executable,'tools/build_path.py']);node=run('path-all-node',['node','--test','tests/core.test.cjs','tests/path.test.cjs']);assert '# fail 0'in node
 run('path-inherited-oracle',[sys.executable,'tests/oracle.py']);run('path-new-oracle',[sys.executable,'tests/path_oracle.py']);run('path-frozen-model',[sys.executable,'training/final_check.py']);run('path-inherited-browser',[sys.executable,'tests/browser.py']);run('path-new-browser',[sys.executable,'tests/path_browser.py']);run('path-demo',[sys.executable,'tools/path_demo.py'])
 demo=json.loads((E/'path-demo.json').read_text());model=json.loads((E/'fresh-evaluation.json').read_text())
 report.update(status='passed',node_tests=int(re.search(r'# tests (\d+)',node)[1]),classic_browser_workflows=json.loads((E/'browser.json').read_text())['count'],path_browser_workflows=json.loads((E/'path-browser.json').read_text())['count'],old_reference_cases=250,new_reference=json.loads((E/'path-oracle.json').read_text()),demo_seconds=demo['seconds'],narration=demo['narration'],frozen_model={'matches':model['top_class_correct'],'cases':model['n'],'note':'Identical prior numeric evaluation rerun, not new held-out data'},scope='Internal synthetic task and browser checks. No learner study or measured educational benefit.',finished_at=datetime.now(timezone.utc).isoformat())
except BaseException as e:report.update(status='failed',error=str(e),traceback=traceback.format_exc());raise
finally:(E/'path-release.json').write_text(json.dumps(report,indent=2))
(R/'judge.html').write_text('''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Counterstep Transfer Path</title><style>body{max-width:940px;margin:45px auto;padding:25px;background:#0b1217;color:#f3f6f6;font:18px/1.6 system-ui}a{color:#b4f3cf}h1{font-size:42px;line-height:1.15}video{width:100%;border-radius:12px}code{overflow-wrap:anywhere}p{max-width:850px}</style><h1>Repair it. Then write it without choices.</h1><p><a href="path.html">Open the new Transfer Path</a> · <a href="index.html">Legacy multiple-choice app</a> · <a href="source.zip">Source and tests</a></p><video controls preload="metadata" src="path-demo.mp4"></video><h2>What is different</h2><p>The old practice was multiple choice. The new path asks for a written step and checks the requested operation, not merely an equivalent final answer. A second card changes the structure. A tutor note preserves the original questions, all responses and requested help.</p><h2>The actual architecture</h2><p>Entered chain → exact rational audit → frozen neural practice-family suggestion (or manual choice) → authored fresh tasks → exact equivalence plus requested-form check → replayable response history → readable tutor note.</p><p>The original checker and learned weights are unchanged. The new layer never turns a model score into correctness. Numerical first-response labels are not mastery, diagnosis or learning gains.</p><p><a href="TRANSFER_PATH.md">New method and limits</a> · <a href="README.md">Original engine and model</a> · <a href="evidence/path-release.json">Executed release</a> · <a href="evidence/path-oracle.json">Independent mathematical checks</a></p><p>1:57 actual-app demonstration with synthetic equations and stock synthetic narration. No classroom or tutor pilot has been conducted.</p></html>''')
with zipfile.ZipFile(R/'source.zip','w',zipfile.ZIP_DEFLATED)as z:
 for f in sorted(R.rglob('*')):
  rel=f.relative_to(R)
  if f.is_file()and f.suffix not in ['.zip','.mp4','.webm','.wav']and not any(x in rel.parts for x in ['__pycache__','build-input','transfer-payload']):z.write(f,rel)
names=['path.html','index.html','src/core.js','src/model.json','src/path.js','src/path-ui.js','TRANSFER_PATH.md','judge.html','source.zip','path-demo.mp4','path-demo-transcript.md','evidence/path-release.json','evidence/path-oracle.json']
(R/'transfer-manifest.json').write_text(json.dumps({n:{'bytes':(R/n).stat().st_size,'sha256':hashlib.sha256((R/n).read_bytes()).hexdigest()}for n in names},indent=2));print(json.dumps(report,indent=2))
