/** Execute the integration, preserve its SQLite files and export observer snapshots. */
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {Lab} from './lab.mjs';import {sha} from '../src/outbox.mjs';
const trace=JSON.parse(fs.readFileSync('public/data/evm-trace.json','utf8'));
const databaseRoot='evidence/outbox-databases/'+new Date().toISOString().replace(/[^0-9]/g,'');
const output={databaseRoot,format:'forkline-outbox-record-v1',generatedAt:new Date().toISOString(),execution:'Node.js SQLite worker + independent SQLite HTTP ticket receiver; block-hash-pinned local-EVM observations',scope:'Rehearsal only. Local fixture tickets are real persisted rows, not real admission tickets or shipments. RPC observations are trusted. No production exactly-once or consensus-finality guarantee.',traceSha256:sha(trace),cases:[]};
async function execute(id,title,actions){const root=path.resolve(databaseRoot,id);if(fs.existsSync(root))throw Error('Refusing to overwrite prior run databases: '+root);const lab=await Lab.create(root,trace);const steps=[];const add=(title)=>steps.push({title,state:lab.snapshot()});try{add('Start two empty delivery databases');for(const [action,title]of actions){await lab.action(action);add(title)}const result={id,title,steps};output.cases.push(result);return result}finally{await lab.close()}}
const observe=[['next','Observe the common deployment'],['next','Observe ALPHA-42 on branch A'],['next','Wait: two confirmations'],['next','Three confirmations: eligible to queue'],['queue','Queue the same command under both policies']];
const a=await execute('before-send','A reorg happens while the command waits in the outbox',[...observe,['next','Before the worker sends, branch A disappears'],['dispatch','Dispatch: enqueue-only issues an orphaned ticket; guarded holds'],['restart','Restart both workers: the hold and ticket survive']]);
let end=a.steps.at(-1).state;assert.equal(end.guard.tickets.length,0);assert.equal(end.naive.tickets.length,1);assert(end.naive.tickets[0].orphaned);assert.equal(end.guard.outbox[0].state,'blocked');
const b=await execute('lost-ack','The receiver commits, the acknowledgement is lost, then the chain changes',[...observe,['drop','Receiver commits each ticket, then drops the HTTP acknowledgement'],['restart','Restart workers: uncertain does not mean undelivered'],['next','Branch A disappears before receipt reconciliation'],['reconcile','Read the receiver receipt without issuing a second ticket'],['next','Branch B extends'],['next','BETA-17 reaches the waiting threshold'],['queue','Guarded queue stays paused after the orphaned acknowledged action'],['next','The old branch returns: the incident must stay latched']]);
end=b.steps.at(-1).state;assert.equal(end.guard.tickets.length,1);assert.equal(end.guard.receipts.length,1);assert.equal(end.guard.incidents.length,1);assert.equal(end.guard.paused,true);assert.equal(end.guard.outbox.length,1);assert.equal(end.guard.outbox[0].attempts,1);
fs.mkdirSync('public/data',{recursive:true});fs.writeFileSync('public/data/outbox-runs.json',JSON.stringify(output,null,2));fs.writeFileSync('evidence/outbox-record.json',JSON.stringify({status:'passed',cases:output.cases.length,databaseRoot,traceSha256:output.traceSha256,checks:['enqueue-only sent one orphan; guarded sent zero','uncertain receipt recovered without second POST','incident remains after prior branch returns','blocked/acknowledged state survives SQLite reopening'],scope:output.scope},null,2));console.log(JSON.stringify({status:'passed',cases:2,files:'evidence/outbox-databases'}));
