const {test}=require('node:test'),A=require('node:assert/strict'),crypto=require('node:crypto');
const R=require('../app/review_state.js');
const c=()=>({schema:'countback-review-case-1',evidence_sha256:'a'.repeat(64),opencv_version:'5.0.0',items:[{id:'mouse',evidence_level:'appearance_only',identity_verified:false,views:[{id:'view-1',image_sha256:'b'.repeat(64),region:null}]},{id:'remote',evidence_level:'internal_pattern_consistent',identity_verified:false,views:[{id:'view-1',image_sha256:'c'.repeat(64),region:null}]}]});
const event=(patch={})=>({reference:'mouse',view:'view-1',verdict:'unclear',note:'Automated test only, not a user decision.',reviewer:'Automated software test',recorded_at:new Date().toISOString(),...patch});
for(const size of [0,1,3,55,56,63,64,65,1000,8193])test(`Offline SHA matches native SHA for ${size} bytes`,()=>{const b=crypto.randomBytes(size);A.equal(R.sha256Bytes(b),crypto.createHash('sha256').update(b).digest('hex'));});
test('Canonical ordering independent of key insertion',()=>A.equal(R.canonical({z:1,a:[3,2]}),R.canonical({a:[3,2],z:1})));
test('NaN is not serializable evidence',()=>A.throws(()=>R.canonical({a:NaN})));
test('Initial human review is empty',async()=>{const x=c(),s=await R.create(x);A.deepEqual(s.events,[]);const h=await R.handoff(x,s);A.deepEqual(h.attention_required,['mouse','remote']);A.equal(h.kit_complete,null);});
test('Human consistency never upgrades machine evidence',async()=>{const x=c(),s=await R.add(x,await R.create(x),event({verdict:'consistent'}));const h=await R.handoff(x,s);A.equal(h.items[0].automated_evidence,'appearance_only');A.deepEqual(h.automated_unresolved,['mouse']);A.equal(h.identity_verified,false);A.equal(h.physical_quantity,null);});
test('Save and reopen exact evidence',async()=>{const x=c(),s=await R.add(x,await R.create(x),event());A.deepEqual(await R.restore(x,await R.pack(x,s)),s);});
test('Evidence change rejects prior session',async()=>{const x=c(),s=await R.pack(x,await R.create(x));x.items[0].views[0].image_sha256='d'.repeat(64);await A.rejects(R.restore(x,s));});
test('Altered payload fails digest',async()=>{const x=c(),p=await R.pack(x,await R.add(x,await R.create(x),event()));p.state.events[0].verdict='consistent';await A.rejects(R.restore(x,p));});
test('Recomputed digest still rejects invented reference',async()=>{const x=c(),p=await R.pack(x,await R.add(x,await R.create(x),event()));p.state.events[0].reference='invented';p.digest=await R.digest(p.state);await A.rejects(R.restore(x,p));});
test('Unknown view rejected',async()=>{const x=c();await A.rejects(R.add(x,await R.create(x),event({view:'view-9'})));});
test('Unknown verdict rejected',async()=>{const x=c();await A.rejects(R.add(x,await R.create(x),event({verdict:'certified'})));});
test('Empty reason rejected',async()=>{const x=c();await A.rejects(R.add(x,await R.create(x),event({note:' '})));});
test('Empty reviewer rejected',async()=>{const x=c();await A.rejects(R.add(x,await R.create(x),event({reviewer:''})));});
test('Overlong reason rejected',async()=>{const x=c();await A.rejects(R.add(x,await R.create(x),event({note:'x'.repeat(1201)})));});
test('Unexpected certification field rejected',async()=>{const x=c();await A.rejects(R.add(x,await R.create(x),event({kit_complete:true})));});
test('Future review time rejected',async()=>{const x=c();await A.rejects(R.add(x,await R.create(x),event({recorded_at:'2099-01-01T00:00:00Z'})));});
test('Corrections retain history and latest view',async()=>{const x=c();let s=await R.add(x,await R.create(x),event({verdict:'consistent'}));s=await R.add(x,s,event({verdict:'different'}));A.equal(s.events.length,2);A.equal((await R.handoff(x,s)).items[0].human_assessment.verdict,'different');});
test('Input state not mutated',async()=>{const x=c(),s=await R.create(x),before=JSON.stringify(s);await R.add(x,s,event());A.equal(JSON.stringify(s),before);});
test('Duplicate reference rejected',async()=>{const x=c();x.items.push(x.items[0]);await A.rejects(R.create(x));});
test('Noncontiguous event sequence rejected',async()=>{const x=c(),s=await R.add(x,await R.create(x),event());s.events[0].sequence=4;await A.rejects(R.validate(x,s));});
test('Unicode and HTML-like notes remain literal data',async()=>{const x=c(),s=await R.add(x,await R.create(x),event({note:'<img src=x onerror=alert(1)> café 😀'}));A.equal((await R.restore(x,await R.pack(x,s))).events[0].note,s.events[0].note);});
test('A look-alike human decision is not kit completeness',async()=>{const x=c();let s=await R.create(x);for(const item of x.items)s=await R.add(x,s,event({reference:item.id,verdict:'consistent'}));const h=await R.handoff(x,s);A.equal(h.human_reviewed_reference_labels,2);A.deepEqual(h.attention_required,[]);A.equal(h.kit_complete,null);A.equal(h.identity_verified,false);});
